#!/bin/bash
fun_badvpn() {
    clear
    echo "            MENU BADVPN             "
    echo ""
    if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
        echo "PORTAS: $(netstat -nplt | grep 'badvpn-ud' | awk {'print $4'} | cut -d: -f2 | xargs)"
    else
        sleep 0.1
    fi
    var_sks1=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo "◉ " || echo "○ ")
    echo ""
    echo "[1] • ACTIVAR BADVPN(NORMAL 7300) $var_sks1 "
    echo "[2] • ABRIR PUERTO"
    echo "[0] • VOLVER"
    echo ""
    echo -ne "O QUE DESEA HAZER ? "
    read resposta
    if [[ "$resposta" = '1' ]]; then
        if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
            clear
            echo "             BADVPN              "
            echo ""
            fun_stopbad () {
                sleep 1
                for pidudpvpn in $(screen -ls | grep ".udpvpn" | awk {'print $1'}); do
                    screen -r -S "$pidudpvpn" -X quit
				done
                [[ $(grep -wc "udpvpn" /etc/autostart) != '0' ]] && {
                    sed -i '/udpvpn/d' /etc/autostart
                }
                sleep 1
                screen -wipe >/dev/null
            }
            echo "DESACTIVANDO EL BADVPN"
            echo ""
            fun_stopbad
            echo ""
            echo "BADVPN DESACTIVADO CON EXITO!"
            sleep 3
            fun_badvpn
        else
            clear
            echo "INICIANDO EL BADVPN... "
            fun_udpon () {
                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8
                [[ $(grep -wc "udpvpn" /etc/autostart) = '0' ]] && {
                    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
                } || {
                    sed -i '/udpvpn/d' /etc/autostart
                    echo -e "ps x | grep 'udpvpn' | grep -v 'grep' || screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 10000 --max-connections-for-client 8 --client-socket-sndbuf 10000" >> /etc/autostart
                }
                sleep 1
            }
            inst_udp () {
                [[ -e "/bin/badvpn-udpgw" ]] && {
                    sleep 0.1
                } || {
                    cd $HOME
                    wget wget https://raw.githubusercontent.com/hayate25/genkkoplus/main/squid/badvpn-udpgw -O badvpn-udpgw -o /dev/null
                    mv -f $HOME/badvpn-udpgw /bin/badvpn-udpgw
                    chmod 777 /bin/badvpn-udpgw
                }
            }
            echo ""
            inst_udp
            fun_udpon
            echo ""
            echo "BADVPN ACTIVADO CON EXITO"
            sleep 3
            fun_badvpn
        fi
    elif [[ "$resposta" = '2' ]]; then
        if ps x | grep -w udpvpn | grep -v grep 1>/dev/null 2>/dev/null; then
            clear
            echo "            BADVPN             "
            echo ""
            echo -ne "CUAL PUERTO DESEA ULTILIZAR ?: "
            read porta
            [[ -z "$porta" ]] && {
                echo ""
                echo "Puerto invalido!"
                sleep 2
                clear
                menu
            }
            echo ""
            echo "INICIANDO el BADVPN en PUERTO $porta"
            echo ""
            fun_abrirptbad() {
                sleep 1
                screen -dmS udpvpn /bin/badvpn-udpgw --listen-addr 127.0.0.1:$porta --max-clients 10000 --max-connections-for-client 8
                sleep 1
            }
            fun_abrirptbad
            echo ""
            echo "BADVPN ACTIVADO CON SUCESSO"
            sleep 2
            fun_badvpn
        else
            clear
            echo "FUNCION NO DISPONIBLE\n\nACTIVE  BADVPN PRIMERO !"
            sleep 2
            fun_badvpn
        fi
    elif [[ "$resposta" = '0' ]]; then
        echo ""
        echo "Retornando..."
        sleep 1
        menu
    else
        echo ""
        echo "Opcion invalida !"
        sleep 1
        fun_badvpn
    fi
}
fun_badvpn