#!/bin/bash
#PATH DE ARCHVOS
dir_token=/etc/token
file_token=$dir_token/BD
file_pass=$dir_token/.passw
file_client=$dir_token/.clientes
#DIRECTORIOS
mkdir_dir (){
  if [ -d $dir_token ]; then
	    echo
	    else
	     mkdir $dir_token
fi
if [ -f $file_token ]; then
	    echo
	    else
	     touch $file_token
       chmod 755 $file_token
fi
if [ -f $file_pass ]; then
	    echo
	    else
	     touch $file_passw
       chmod 755 $file_pass
fi
if [ -f $file_client ]; then
	    echo
	    else
	     touch $file_client
       chmod 755 $file_client
fi
}
#HORA DE MEXICO
echo "America/Mexico_City" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Mexico_City /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
#MENSAJE DE BINEVENIDA
msg () {
echo -e "#########################################"
    echo -e "#    Bienvenido, Gracias por utilizar Onlycode VPN     #"
    echo -e "#    Este SCRIPT autoriza su TOKEN ID para usar        #"
    echo -e "#    Nuestra apk...                                    #"
    echo -e "#   -----------------------------------------------    #"
    echo -e "#          dev: @dankelthaher - Onlycode VPN           #"
    echo -e "############################################"
}
#DEFINE CONTRASEÑA UNICA
define (){
	mkdir_dir
echo -e "------------------------------------------------------"
echo -e "ANTES DE COMENZAR DEBE ingresar UNA contraseña"
echo -e "------------------------------------------------------"
read -p "[ingrese]: " pass
echo -e "$pass" >> $file_pass
echo -e "------------------------------------------------------"
}
#FUNCION DE CREACION DE USUARIOS
crear () {
    clear
    TITLE="Onlycode VPN"
echo -e "$TITLE"
echo -e ""
echo -e " AUTORIZAR TOKEN ID"
echo -e "------------------------------------------------------"
echo -e ""
echo -e "Ingrese el Nombre del Usuario"
echo -e "------------------------------------------------------"
read -p "  [ingrese]: " usr
echo -e "------------------------------------------------------"
echo -e "Ingrese el TOKEN que desea Autorizar"
echo -e "------------------------------------------------------"
read -p "  [TOKEN ID]: " token

# Check If Username Exist, Else Proceed
egrep "^$token" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
clear
echo -e "------------------------------------------------------"
echo -e "$TITLE"
echo ""
echo -e " El TOKEN ya existe en su servidor, intente con otro Token."
exit 0
else
echo -e "------------------------------------------------------"
read -p "  Dias activos: " Days
echo -e "------------------------------------------------------"
clear
sleep 1
IPADDR=$(wget -4qO- http://ipinfo.io/ip)
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g' )"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
stunnel4port="$(netstat -nlpt | grep -i stunnel4 | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
pyport="$(netstat -nlpt | grep -i python | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
squidport="$(cat /etc/squid/squid.conf | grep -i http_port | awk '{print $2}' | xargs | sed -e 's/ /, /g')"
useradd -m -s /bin/false -e $Expiration $token > /dev/null
egrep "^$token" /etc/passwd &> /dev/null
DIA=`date +"%d/%m/%Y"`
HORA=`date +"%H:%M"`
echo -e "$(cat $file_pass)\n$(cat $file_pass)\n" | passwd $token &> /dev/null
echo -e "$token" >> $file_token
echo -e "$usr  $token  $DIA     $HORA"  >> $file_client
clear
echo -e "------------------------------------------------------"
echo -e "$TITLE"
echo -e "------------------------------------------------------"
echo ""
echo -e " Datos del Usuario:"
echo -e "  Token ID: "$token
echo -e "  Caducidad de la cuenta: "$Expiration_Display
echo -e ""
echo -e "------------------------------------------------------"
echo -e "  Host/IP: "$IPADDR
echo -e "  Puerto OpenSSH: "$opensshport
echo -e "  Puerto Dropbear: "$dropbearport
echo -e "  Puerto SSL: "$stunnel4port
echo -e "  Puertos Squid: "$squidport
echo -e "  Puertos Openvpn: "$openvpnport
echo -e "  Puertos python: "$pyport
echo -e "------------------------------------------------------"
fi
}
#ELIMINAR ID
eliminar () {
  unset token
  echo -e "$TITLE"
echo -e ""
    i=1
	for total in `cat $file_token`; do
	[[ -f "$total" ]] && continue
	option_id[$i]="$total"
    echo -e "------------------------------------------------------"
	echo -e " [$i] > $total"
	let i++
    done
	i=$(($i - 1))
    echo -e "------------------------------------------------------"
	while [[ -z ${option_id[$slct_option]} ]]; do
read -p "seleccione [1-$i]: " slct_option
tput cuu1 && tput dl1
done
token="${option_id[$slct_option]}"
sleep 2
egrep "^$token" /etc/passwd &> /dev/null
if [ $? -eq 0 ]; then
  userdel -f $token
  rm -rf /home/$token
  sed -i "s;$token;;g" $file_token
  sed -i '/^$/d' $file_token
  sed -i "/$token/d" $file_client
  sed -i '/^$/d' $file_client
	clear
	echo -e ""
  echo -e "$TITLE"
  echo -e "------------------------------------------------------"
	echo -e " TOKEN Eliminado con Exito"
	echo -e "------------------------------------------------------"
else
	clear
	echo -e ""
  echo -e "$TITLE"
  echo -e "------------------------------------------------------"
	echo -e " El TOKEN que ingresaste no existe"
	echo -e "------------------------------------------------------"
fi
}
#EDITAR TOKEN
editar (){
unset token
  echo -e "$TITLE"
echo -e ""
    i=1
	for total in `cat $file_token`; do
	[[ -f "$total" ]] && continue
	option_id[$i]="$total"
    echo -e "------------------------------------------------------"
	echo -e " [$i] > $total"
	let i++
    done
	i=$(($i - 1))
    echo -e "------------------------------------------------------"
	while [[ -z ${option_id[$slct_option]} ]]; do
read -p "seleccione [1-$i]: " slct_option
tput cuu1 && tput dl1
done
token="${option_id[$slct_option]}"
sleep 2
egrep "^$token" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
echo -e "Ingrese el numero de dias"
echo -e "------------------------------------------------------"
read -p " [Días]: " Days
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
passwd -u $token
usermod -e $Expiration $token
egrep "^$token" /etc/passwd >/dev/null
echo -e "$PASSWDT\n$PASSWDT\n"|passwd $token &> /dev/null
clear
echo -e "$TILTE"
echo -e "------------------------------------------------------"
echo -e ""
echo -e " token ID: $token"
echo -e "------------------------------------------------------"
echo -e " Caducidad de cuenta modificada: $Days Dias"
echo -e "------------------------------------------------------"
echo -e " La cuenta vence el: $Expiration_Display"
echo -e "------------------------------------------------------"
else
clear
echo -e "$TILTE"
echo -e "------------------------------------------------------"
echo -e ""
echo -e " El Token que ingresaste no existe"
echo -e ""
fi
}
#MOSTAR USURIOS
lista (){
	if [ -f /etc/debian_version ]; then
	UIDN=1000
elif [ -f /etc/redhat-release ]; then
	UIDN=500
elif [ -f /etc/ubuntu_version ]; then
	UIDN=500
else
	UIDN=500
fi
clear
echo -e "$TILTE"
echo -e "------------------------------------------------------"
echo -e ""
echo -e " TOKEN ID               Expiracion"
echo -e "------------------------------------------------------"
while read Checklist
do
        Spacer=""
        Account="$(echo $Checklist | cut -d: -f1)"
        ID="$(echo $Checklist | grep -v nobody | cut -d: -f3)"
        Exp="$(chage -l $Account | grep "Account expires" | awk -F": " '{print $2}')"
        if [[ $ID -ge $UIDN ]]; then
        echo -e " $Account   " "   $Exp"
        fi
done < /etc/passwd
No_Users="$(awk -F: '$3 >= '$UIDN' && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo -e "------------------------------------------------------"
echo -e " Numero de TOKENS: "$No_Users
echo -e "------------------------------------------------------"
echo -ne "\nARGENTINA VPS1: wep!\nENTER para VOLVER al MENU!"; read
}
#ELIMINAR EXPIRADOS
expirados () {
clear
unset token
echo -e ""
echo -e "$TITLE"
echo -e "------------------------------------------------------"

datenow=$(date +%s)
for token in $(awk -F: '{print $1}' /etc/passwd); do
expdate=$(chage -l $token|awk -F: '/Account expires/{print $2}')
echo $expdate | grep -q never && continue
echo -n "Token \`$token' expira el $expdate ... "
expsec=$(date +%s --date="$expdate")
diff=$(echo $datenow - $expsec|bc -l)
echo $diff | grep -q ^\- && echo okay && continue
userdel -r -f $token  &> /dev/null
done
echo -e ""
echo -e "  Todos Los TOKEN expirados han sido Eliminados"
echo -e "------------------------------------------------------"
}
informacion_clientes () {
     echo -e "               INFORMACION DE CLIENTES                 "
    echo -e "------------------------------------------------------"
    cat $file_client | column -t
    echo -e "------------------------------------------------------"
    echo -e ""
    echo -e "$TITLE"
    echo -e "------------------------------------------------------"
   echo -ne "\nARGENTINA VPS2: wep!\nENTER para VOLVER al MENU!"; read
}
online (){
clear
TITLE="Onlycode VPN"

if [ -e "/var/log/auth.log" ]; then
        LOG="/var/log/auth.log";
fi
if [ -e "/var/log/secure" ]; then
        LOG="/var/log/secure";
fi

data=( `ps aux | grep -i dropbear | awk '{print $2}'`)
     echo -e "        Usuarios ONLINE Dropbear                "
    echo -e "------------------------------------------------------"
    echo ""
cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt
for PID in "${data[@]}"
do
        cat /tmp/login-db.txt | grep "dropbear\[$PID\]" > /tmp/login-db-pid.txt
        NUM=`cat /tmp/login-db-pid.txt | wc -l`
        USER=`cat /tmp/login-db-pid.txt | awk '{print $10}'`
        IP=`cat /tmp/login-db-pid.txt | awk '{print $12}'`
        if [ $NUM -eq 1 ]; then
                echo -e "Token: $USER - [ON] -"
                fi
done
echo ""
     echo -e "         Usuarios ONLINE OpenSSH                "
    echo -e "------------------------------------------------------"
    echo ""
cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/logins-db.txt
data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

for PID in "${data[@]}"
do
        cat /tmp/logins-db.txt | grep "sshd\[$PID\]" > /tmp/login-db-pid.txt;
        NUM=`cat /tmp/login-db-pid.txt | wc -l`;
        USER=`cat /tmp/login-db-pid.txt | awk '{print $9}'`;
        IP=`cat /tmp/login-db-pid.txt | awk '{print $11}'`;
        if [ $NUM -eq 1 ]; then
                echo -e "Token: $USER - [ON] -";
        fi
done
if [ -f "/etc/openvpn/openvpn-status.log" ]; then
        line=`cat /etc/openvpn/openvpn-status.log | wc -l`
        a=$((3+((line-8)/2)))
        b=$(((line-8)/2))
        echo ""
        echo -e "          Usuarios ONLINE Openvpn               "
    echo -e "------------------------------------------------------"
    echo ""
        cat /etc/openvpn/openvpn-status.log | head -n $a | tail -n $b | cut -d "," -f 1,2,5 | sed -e 's/,/   /g' > /tmp/vpn-login-db.txt
        cat /tmp/vpn-login-db.txt
fi

echo " "
echo " "
echo -ne "\nARGENTINA VPS3: wep!\nENTER para VOLVER al MENU!"; read
}
No_token="$(cat /etc/token/BD | wc -l)"
#MENU DE USUARIOS
menu () {
  clear
echo -e "               == Token Auth == (onlycode)
------------------------------------------------------
TOTAL DE REGISTROS: > TOKEN: $No_token
------------------- = MENU = ------------------------
[1] > AGREGAR TOKEN
[2] > ELIMINAR TOKEN
[3] > EDITAR FECHA TOKEN
[4] > LISTA de TOKEN
[5] > ELIMINAR TOKEN Expirados
[6] > Informacion de Clientes
[7] > TOKEN ONLINES
[0] > SALIR al Menu
------------------------------------------------------"
read -p "seleccione [0-7]: " selection
case "$selection" in
	1)crear ;;
	2)eliminar ;;
  3)editar ;;
  4)lista;;
  5)expirados ;;
  6)informacion_clientes;;
  7)online;;
	0)cd $HOME && exit 0;;
	*)
	echo -e " Porfavor seleccione del [0-5]"
	;;
esac
}
if [ -f $file_pass ]; then
	    echo
	    else
    define
fi
msg
menu