#!/bin/bash
#===================================================
#	SCRIPT: Optimizar GENKKOSSH MANAGER
#	Desarrollado por :	GENKKOSSH
#	CONTATO TELEGRAM:	http://t.me/HAYATEGENKK
#===================================================
fun_bar() {
	comando[0]="$1"
	comando[1]="$2"
	(
		[[ -e $HOME/fim ]] && rm $HOME/fim
		${comando[0]} -y >/dev/null 2>&1
		${comando[1]} -y >/dev/null 2>&1
		touch $HOME/fim
	) >/dev/null 2>&1 &
	tput civis
	echo -ne "     AGUARDE - ["
	while true; do
		for ((i = 0; i < 18; i++)); do
			echo -ne "#"
			sleep 0.1s
		done
		[[ -e $HOME/fim ]] && rm $HOME/fim && break
		echo -e "]"
		sleep 1s
		tput cuu1
		tput dl1
		echo -ne "     AGUARDE - ["
	done
	echo -e "] - OK !"
	tput cnorm
}
[[ $(grep -wc mlocate /var/lib/dpkg/statoverride) != '0' ]] && sed -i '/mlocate/d' /var/lib/dpkg/statoverride
clear
echo -e "                Optimizar servidor               "
echo ""
echo -e "               Actualización de paquetes"
echo ""
fun_bar 'apt-get update -y' 'apt-get upgrade -y'
echo ""
echo -e "      Corrigiendo problemas de dependencias"
echo ""
fun_bar 'apt-get -f install'
echo ""
echo -e "            Removiendo paquete inútiles"
echo ""
fun_bar 'apt-get autoremove -y' 'apt-get autoclean -y'
echo ""
echo -e "        Removiendo Paquete con problemas"
echo ""
fun_bar 'apt-get -f remove -y' 'apt-get clean -y'
clear
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
MEM1=$(free | awk '/Mem:/ {print int(100*$3/$2)}')
ram1=$(free -h | grep -i mem | awk {'print $2'})
ram2=$(free -h | grep -i mem | awk {'print $4'})
ram3=$(free -h | grep -i mem | awk {'print $3'})
swap1=$(free -h | grep -i swap | awk {'print $2'})
swap2=$(free -h | grep -i swap | awk {'print $4'})
swap3=$(free -h | grep -i swap | awk {'print $3'})
echo -e "•Memoria RAM•                    •Swap•"
echo -e " Total: $ram1                   Total: $swap1"
echo -e " En Uso: $ram3                  Em Uso: $swap3"
echo -e " Libre: $ram2                   Livre: $swap2"
echo ""
echo -e "Memoria ram antes de optimizar:" $MEM1%
echo ""
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
sleep 2
echo ""
fun_limpram() {
	sync
	echo 3 >/proc/sys/vm/drop_caches
	sync && sysctl -w vm.drop_caches=3
	sysctl -w vm.drop_caches=0
	swapoff -a
	swapon -a
	sleep 4
}
function aguarde() {
	sleep 1
	helice() {
		fun_limpram >/dev/null 2>&1 &
		tput civis
		while [ -d /proc/$! ]; do
			for i in / - \\ \|; do
				sleep .1
				echo -ne "\e[1D$i"
			done
		done
		tput cnorm
	}
	echo -ne "Limpiando la MEMORIA RAM y SWAP... "
	helice
	echo -e "\e[1DOk"
}
aguarde
sleep 1
clear
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
MEM2=$(free | awk '/Mem:/ {print int(100*$3/$2)}')
ram1=$(free -h | grep -i mem | awk {'print $2'})
ram2=$(free -h | grep -i mem | awk {'print $4'})
ram3=$(free -h | grep -i mem | awk {'print $3'})
swap1=$(free -h | grep -i swap | awk {'print $2'})
swap2=$(free -h | grep -i swap | awk {'print $4'})
swap3=$(free -h | grep -i swap | awk {'print $3'})
echo -e "•Memoria RAM•                    •Swap•"
echo -e " Total: $ram1                   Total: $swap1"
echo -e " En Uso: $ram3                  Em Uso: $swap3"
echo -e " Libre: $ram2                   Livre: $swap2"
echo ""
echo -e "Memória RAM después de Optimizar:" $MEM2%
echo ""
echo -e "Economia de : $(expr $MEM1 - $MEM2)%"
echo ""
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"